export const Keywords = {
  ELSE: "else",
  WHILE: "while",
  IMPORT: "import",
  IF: "if",
  FOR: "for",
  DO: "do",
  THROW: "throw",
  CLASS: "class",
  SWITCH: "switch",
  LET: "let",
  CONST: "const",
  VAR: "var",
  EXPORT: "export",
  TRY: "try",
  DEFAULT: "default",
  CATCH: "catch",
  FROM: "from",
  FINALLY: "finally",
  FUNCTION: "function",
};
