export const Symbols = {
  SEMICOLON: ';',
  NEW_LINE: '\n',
  DOT: '.',
  OPENING_PARENTHESIS: '(',
  CLOSING_PARENTHESIS: ')',
  OPENING_BRACE: '{',
  CLOSING_BRACE: '}',
  OPENING_BRACKET: '[',
  CLOSING_BRACKET: ']',
  SPACE: ' ',
  COMMA: ',',
  PLUS: '+',
  OPENING_ANGLE: '<',
  CLOSING_ANGLE: '>',
  LAMBDA: '=>',
  EXCLAMATION_MARK: '!',
  QUESTION_MARK: '?',
  NOTHING: ''
};
